spring: 
  datasource: 
    hikari: 
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa 
      maximum-pool-size: 5 
      minimum-idle: 1 
      pool-name: hikari 
  h2: 
    console: 
      path: /h2console 
      enabled: true 
      
server:
  port: 9998
  
szs:
  scrap-url: https://codetest.3o3.co.kr/scrap/
    
jpa: 
  hibernate: 
    ddl-auto: update 
  show-sql: true 
  properties: 
    hibernate: 
      format_sql: true

  
springdoc:
  swagger-ui:
    path: /swagger-ui.html


secretkey:
  password-key: 1234567890123456
  reg-no-key: 9876543210987654
  jwt-key: jwtsecretkey